apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: boardgame
  namespace: webapps  # Optional: remove if using default namespace
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
      - name: boardgame
        image: saikumar0803/boardgame_canary:v1 
        ports:
        - containerPort: 8080
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      steps:
      - setWeight: 20
      - pause: { duration: 1m }
      - setWeight: 50
      - pause: { duration: 1m }
      - setWeight: 100


---
#svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: boardgame-svc
spec:
  selector:
    app: boardgame
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

